version: '3'

services:
# Serviço Web do Nginx para os arquivos estáticos
  webserver-static:
    container_name: webserver-static
    build:
      context: ./web/static-webserver
      dockerfile: Dockerfile
    ports:
      - '8009:80'
    volumes:
      - './web/static-webserver/html:/usr/share/nginx/html'

# Serviço de banco de dados com PostgreSQL
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    # volumes:
    #   - ./database/pgdata:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"

  # Serviço do Laravel 10
  # O host 'database' se refere ao nome do servico do banco de dados, descrito acima
  api:
    container_name: api
    build:
      args:
          user: user
          uid: 1000
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: 5432
      DB_DATABASE: ${DATABASE_NAME}
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${API_JWT_SECRET}
      APP_KEY: ${API_APP_KEY}
    volumes:
      - ./api:/var/www/
    working_dir: /var/www
    depends_on:
      - database
      - webserver-api

  # Serviço do Nginx para o Laravel 10
  webserver-api:
    image: nginx:alpine
    container_name: webserver-api
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./api:/var/www
      - ./web/api-webserver:/etc/nginx/conf.d/