version: '3'

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    volumes:
      - './web/html:/usr/share/nginx/html'
  # Serviço do PostgreSQL
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: educara-db
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    ports:
      - "8002:5432"
  # Serviço do Spring Boot
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    depends_on:
      - database
