version: '3'

services:
# Serviço Web do Nginx
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    volumes:
      - './web/html:/usr/share/nginx/html'

# Serviço do PostgreSQL
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"

  # Serviço do Laravel
  # O host 'database' se refere ao nome do servico do banco de dados, descrito acima
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
          - DB_HOST=database
          - DB_USERNAME=${DATABASE_USERNAME}
          - DB_PASSWORD=${DATABASE_PASSWORD}
          - DB_PORT=5432
          - DB_DATABASE=${DATABASE_NAME}
          - JWT_SECRET=${JWT_SECRET}
          - COMPOSER_HOME=/composer
          - COMPOSER_ALLOW_SUPERUSER=1
          - APP_ENV=local
          - APP_KEY=${APP_KEY}
    volumes:
      - ./api:/var/www/application
    working_dir: /var/www
    depends_on:
      - database